### ISSUE TITLE
Docker compose exited with code 0

### ISSUE THREAD

**Issue by jase64** [mage-ai/compose-quickstart#1]
Hi,

I tried to start Mage using the provided docker compose templates in a VM. However, several attempts ended in 

```
sja@debian:~$ sudo docker compose --verbose  up
[+] Running 1/0
 ✔ Container sja-magic-1  Created                                                                                                                                                               0.0s 
Attaching to magic-1
magic-1 exited with code 0
```
No container running
```
sja@debian:~$ sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

VM spec:
- 8 Gb RAM
- 6 vcores
- 20 Gb disk

docker-compose.yml
```
version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/sja/${PROJECT_NAME}
      ENV: .env
    ports:
      - 6789:6789
    volumes:
      - .:/home/sja
    restart: on-failure:5
```

Dockerfile
```
FROM mageai/mageai:latest

ARG USER_CODE_PATH=/home/sja/${PROJECT_NAME}

# Note: this overwrites the requirements.txt file in your new project on first run. 
# You can delete this line for the second run :) 
COPY requirements.txt ${USER_CODE_PATH}/requirements.txt 

RUN pip3 install -r ${USER_CODE_PATH}/requirements.txt
```

.env
```
PROJECT_NAME=TEST
```

Further a docker compose log returns nothing.
```
sja@debian:~$ sudo docker compose logs magic
```

Am I missing something? Thanks.

**Comment by mattppal** [comment]
Hi @jase64, looks like you modified the `USER_CODE_PATH` and a few other paths in your project. Mage uses `home/src`, so it's likely that's interfering with the container. 

I would recommend starting with the Docker compose template [here](https://docs.mage.ai/getting-started/setup#get-mage). If that doesn't work, please let us know and I'll be happy to provide support.

**Comment by jase64** [comment]
Hi @mattppal,

Thanks for your hints.

I did as instructed:
a) moved all files to /home/src
b) change rights of folder public (chmod 777)
c) modified my files accordingly
Dockerfile
```
FROM mageai/mageai:latest

ARG USER_CODE_PATH=/home/src/${PROJECT_NAME}

# Note: this overwrites the requirements.txt file in your new project on first run. 
# You can delete this line for the second run :) 
COPY requirements.txt ${USER_CODE_PATH}/requirements.txt 

RUN pip3 install -r ${USER_CODE_PATH}/requirements.txt
```

docker-compose.yml
```
version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: .env
    ports:
      - 6789:6789
    volumes:
      - .:/home/src
    restart: on-failure:5
```
requirements.txt is an empty file (for now).
.env
```
PROJECT_NAME=test
```

d) launched the container in /home/src
```
sja@debian:/home/src$ sudo docker compose up
[+] Running 1/1
 ✔ Container src-magic-1  Recreated                                                                                                                                                             0.2s 
Attaching to magic-1
magic-1 exited with code 0
sja@debian:/home/src$ sudo docker ps
CONTAINER ID   IMAGE                  COMMAND             CREATED         STATUS                  PORTS                                                 NAMES
0ed4668633f3   mageai/mageai:latest   "mage start test"   7 seconds ago   Up Less than a second   0.0.0.0:6789->6789/tcp, :::6789->6789/tcp, 7789/tcp   src-magic-1
sja@debian:/home/src$ sudo docker ps
CONTAINER ID   IMAGE                  COMMAND             CREATED          STATUS                                    PORTS     NAMES
0ed4668633f3   mageai/mageai:latest   "mage start test"   11 seconds ago   Restarting (132) Less than a second ago             src-magic-1
sja@debian:/home/src$ sudo docker ps
CONTAINER ID   IMAGE                  COMMAND             CREATED          STATUS                  PORTS                                                 NAMES
0ed4668633f3   mageai/mageai:latest   "mage start test"   14 seconds ago   Up Less than a second   0.0.0.0:6789->6789/tcp, :::6789->6789/tcp, 7789/tcp   src-magic-1
sja@debian:/home/src$ sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
As you see, the container started but unfortunately didn't survive long.

I experience this with all mage.ai images > version 0.9.45.

I also tried to come back to "basics". Not much success that way either.
```
sja@debian:/home/src$ sudo docker run -it -p 6789:6789 -v $(pwd):/home/src mageai/mageai /app/run_app.sh mage start test
Execute command: mage start test
/app/run_app.sh: line 53:     7 Illegal instruction     (core dumped) "$@"
```

At last, I tried with your recommended script, but...
```
sja@debian:/home/src/mage-quickstart$ git clone https://github.com/mage-ai/compose-quickstart.git mage-quickstart && cd mage-quickstart && cp dev.env .env && rm dev.env && sudo docker compose up
Cloning into 'mage-quickstart'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 16 (delta 3), reused 7 (delta 0), pack-reused 0
Receiving objects: 100% (16/16), 4.33 KiB | 4.33 MiB/s, done.
Resolving deltas: 100% (3/3), done.
WARN[0000] The "ENV" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ✔ Container mage-quickstart-magic-1  Recreated                                                                                                                                                 0.2s 
Attaching to magic-1
magic-1 exited with code 0
sja@debian:/home/src/mage-quickstart/mage-quickstart$ sudo docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS                          PORTS     NAMES
761367fcacfd   mageai/mageai:latest   "mage start your_fir…"   10 seconds ago   Restarting (132) 1 second ago             mage-quickstart-magic-1
sja@debian:/home/src/mage-quickstart/mage-quickstart$ sudo docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS                                    PORTS     NAMES
761367fcacfd   mageai/mageai:latest   "mage start your_fir…"   12 seconds ago   Restarting (132) Less than a second ago             mage-quickstart-magic-1
sja@debian:/home/src/mage-quickstart/mage-quickstart$ sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

Could it be a specific behaviour in Debian 11?
